### PR TITLE
Add pre-commit

### LINKED ISSUE #154: Add a pre-commit
Read more on pre-commit [here](https://pre-commit.com/).

Sub-Issue of #150 

Blocking: #151 , #152

### PR DESCRIPTION
**Pull request by DavisRayM**
# Changes implemented

- [x] Added pre-commit
- [x] Configured pylint and flake8 on pre-commit
- [x] Ran `trailing-whitespace` and `end-of-file-fixer` pre-commits on all files

Closes #154

### CODE REVIEW

**Comment by DavisRayM** [comment]
> We should add something to the docs about prr-commit. i.e. one needs to run pre-commit install of they want to contribute

Totally agree. Wasn't able to locate a particular file to add those instructions, created #158 to cover implementing the necessary information required to contribute to this package.

**Comment by DavisRayM** [comment]
> > We should add something to the docs about prr-commit. i.e. one needs to run pre-commit install of they want to contribute
> 
> Totally agree. Wasn't able to locate a particular file to add those instructions, created #158 to cover implementing the necessary information required to contribute to this package.

@moshthepitt any suggestion of where the information should currently be situated ?

**Comment by moshthepitt** [comment]
Maybe add a contributing.md file in the docs directory and link to it from the main readme?

**Comment by DavisRayM** [comment]
> Maybe add a contributing.md file in the docs directory and link to it from the main readme?

Alright, I'll add this as a task for #158. I'll probably pick that up next and get it in the repo.

**Pull request merged**
